// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASnjJLcVrwFv4RjWsk9zarm8TuDrJL4ms',
    appId: '1:984347631724:web:f9d46841a6fda45f017849',
    messagingSenderId: '984347631724',
    projectId: 'geosustain-4c722',
    authDomain: 'geosustain-4c722.firebaseapp.com',
    storageBucket: 'geosustain-4c722.firebasestorage.app',
    measurementId: 'G-JCMXN40FWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8E55YXDTfqJEolT3gauPeqT6C60avBCQ',
    appId: '1:984347631724:android:80a3dbc996316c06017849',
    messagingSenderId: '984347631724',
    projectId: 'geosustain-4c722',
    storageBucket: 'geosustain-4c722.firebasestorage.app',
  );
}
